### ISSUE TITLE
gotify-broadcast as a plugin to be an "application" relay to different user

### ISSUE THREAD

**Issue by StarZNighT** [eternal-flame-AD/gotify-broadcast#10] opened 2024-07-16 19:20 UTC
As the title says, is there a way to implement broadcasting to x users the same message recieved from another "Application".
For example i've got gotify-smtp installed and would like to send the same message i recieve to other users too.
So an implementation (if possible) would be that if this plugin is able to read inside the given application token and listen into that "channel" (app/token) for incoming notification and spam them to other users.
I hope to be clear.
Could this be implementable?

**Comment by eternal-flame-AD** [comment] 2024-07-16 21:54
@StarZNighT Thanks for the issue, I get what you mean, I'm currently busy but I should be able to look at it by Thursday!

**Comment by eternal-flame-AD** [comment] 2024-07-17 23:00
@StarZNighT 

So currently I don't think there is a way for a plugin to directly intervene with other applications or plugins. However these may work for your purpose:
- Wire things up through the external API: you make something new or fork gotify-smtp to call the external gotify API. It is hacky but gotify API is pretty stable you should be able to last a long time with it. I took a quick peek at gotify-smtp the code is not that complex. If you are interested in learning Go you can try play around with it.
- This one probably is most elegant but I'm not sure if I will have enough time to implement it in the near future. I would be more than happy to accept a PR / collaborated PR. I can do exactly what gotify/server did: make an API repo and then ask other plugins to pull my API repo in and now they can talk to my plugin. This of course still need the adoption from the other plugin developer.
- Make a "patchwire"-like thing: Now Gotify supports message extras, you can write a separate program and use the extras field to route these massage back to the plugin you want to notify.
- Put up an issue on gotify to request a plugin API extension. I am on the Gotify team but I have not been active there for quite some time. Gotify is pretty strong with their goal of simplicity and ease of use. I am not very confident you can get this merged in officially.

**Comment by eternal-flame-AD** [comment] 2024-07-17 23:03
Applications (and to a lesser degree, plugins) are very parasitic in gotify, they don't really have the capability to see inside the system and thus don't really have access to the messages by design.

**Comment by StarZNighT** [comment] 2024-07-20 09:18
I'm going to pull a request on the main gotify server repo thank you so much!

**Comment by eternal-flame-AD** [comment] 2024-07-26 11:22
> I'm going to write a new ticket on the main gotify server repo thank you so much!

Great! I am closing this for now because it seems you intend to look for upstream solutions. I am editing your original issue to add some keywords so if more people have the same requests they can find this and I can reconsider it. If you still want to discuss feel free to respond, I don't mind. I may reopen this if further discussion leads to it.

**Closed by eternal-flame-AD** 2024-07-26 11:22 UTC
